if(NOT DEFINED NAME OR NOT DEFINED ARCH)
    message(FATAL_ERROR "NAME and ARCH are required")
endif()
if(GINCY_WIN AND ARCH EQUAL 32)
    set(expected "gmsv_gincy_core_win32.dll")
elseif(GINCY_WIN AND ARCH EQUAL 64)
    set(expected "gmsv_gincy_core_win64.dll")
elseif(ARCH EQUAL 64)
    set(expected "gmsv_gincy_core_linux64.dll")
else()
    set(expected "gmsv_gincy_core_linux.dll")
endif()
if(NOT NAME STREQUAL expected)
    message(FATAL_ERROR "Binary ${NAME} does not match architecture ${ARCH}. Expected ${expected}.")
endif()
message(STATUS "Native output ${NAME} matches ${ARCH}-bit")
