# Gincy release layout validation.
# cmake -DROOT=<dir> -P tools/validate_release.cmake
cmake_minimum_required(VERSION 3.20)
if(NOT ROOT)
    get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
set(fail "")
function(need_file rel)
    if(NOT EXISTS "${ROOT}/${rel}")
        set(fail "${fail}\n  missing ${rel}" PARENT_SCOPE)
    endif()
endfunction()
function(need_absent rel)
    if(EXISTS "${ROOT}/${rel}")
        set(fail "${fail}\n  unexpected ${rel}" PARENT_SCOPE)
    endif()
endfunction()
need_file("source/CMakeLists.txt")
need_file("source/src/package.cpp")
need_file("source/src/gvm.cpp")
need_file("source/src/cli.cpp")
need_file("source/src/module.cpp")
need_file("source/version.json")
need_file("garrysmod/gamemodes/gincy/gamemode/shared.lua")
need_file("garrysmod/gamemodes/gincy/gamemode/core/sh_gvm.lua")
need_file("garrysmod/lua/bin/gmsv_gincy_core_win32.dll")
need_file("garrysmod/lua/bin/gmsv_gincy_core_win64.dll")
need_file("garrysmod/lua/bin/gmsv_gincy_core_linux.dll")
need_file("garrysmod/lua/bin/gmsv_gincy_core_linux64.dll")
need_absent("garrysmod/gincy_modules")
need_absent("garrysmod/data/gincy/identity/private.pem")
need_absent("build")
need_absent("build-win32")
need_absent("build-win64")
need_absent("native")
file(GLOB py_req "${ROOT}/garrysmod/**/requirements.txt")
if(py_req)
    set(fail "${fail}\n  python requirements in garrysmod")
endif()
file(READ "${ROOT}/source/version.json" json)
string(JSON PRODUCT GET "${json}" product)
if(NOT PRODUCT STREQUAL "3.2.0")
    set(fail "${fail}\n  version.json product ${PRODUCT}")
endif()
file(READ "${ROOT}/garrysmod/gamemodes/gincy/gamemode/core/sh_version.lua" version_lua)
if(NOT version_lua MATCHES "Product = \"3.2.0\"")
    set(fail "${fail}\n  sh_version.lua drifted")
endif()
file(GLOB_RECURSE secrets "${ROOT}/*.pem")
foreach(path IN LISTS secrets)
    file(RELATIVE_PATH rel "${ROOT}" "${path}")
    if(rel MATCHES "tests/" OR rel MATCHES "identity/")
        set(fail "${fail}\n  secret ${rel}")
    endif()
endforeach()
if(fail)
    message(FATAL_ERROR "Gincy Release Validation failed:${fail}")
endif()
message("Gincy Release Validation")
message("----------------------------------------")
message("")
message("Structure          OK")
message("Source             OK")
message("Gamemode           OK")
message("Windows x86        OK")
message("Windows x64        OK")
message("Linux targets      OK")
message("Native deps        OK")
message("Version sync       OK")
message("Package V2         OK")
message("Protection         OK")
message("Secrets            OK")
message("Build garbage      NONE")
message("")
message("Result: READY")
